### ISSUE TITLE
WDL or Nextflow training is included or not?

### ISSUE THREAD

**Issue by Shicheng-Guo** [sdsc/sdsc-summer-institute-2021#44]
WDL or Nextflow training in SDSC is included or not?

**Comment by mkandes** [comment]
Hi Schicheng,

As I mentioned in my email reply, I don't believe I know anyone with NextFlow experience at SDSC. Same with WDL. But you are free to try them out on our systems. If you need assitance setting them up, please reply to the ticket you opened.

Thanks,

Marty Kandes
SDSC HPC User Services Group
